### ISSUE TITLE
cannot fetch to render to page

### ISSUE THREAD

**Issue by nickykwn** [nickykwn/project4#4]
I am able to fetch my api correctly and display the entire json file when I do localhost:3000/fighters. I am currently trying to test to see if I can display all the fighters from my api through react to my localhost:3000. I am geting an error of App.jsx:21Uncaught ReferenceError: string is not defined(…).
I think my object of information is not being changed correctly to a string. 

The code that is giving me a problem is 
 getFighters() {
    fetch('http://ufc-data-api.ufc.com/api/v1/us/fighters', {
      method: 'GET',
      headers: {
        'Content-type': 'application/json; charset=UTF-8',
        'mode': 'no-cors'
      },
      body: JSON.stringify({ 'string': string }),
    })
    .then(r => r.json())
    .then((data) => {
      this.setState({
        fighters: data,
      })
    })
    .catch((err) => console.log(err))
  }

I have been using my previous labs such as the puppies react solution, along with my project 3 and my other labs. But there are many different solutions. I see that for certain labs they would fetch from a created an api from the back end but my api is just a public api that does not require a key. I am not sure if I'm able to fetch the same way. I have also reached out to my fellow classmates but still have not gotten a solution.

**Comment by nickykwn** [comment]
@gittheking @jasonseminara @rapala61 @trevorpreston @irwintsay @mgershowitz

**Comment by gittheking** [comment]
Commenting to format code
```
getFighters() {
  fetch('http://ufc-data-api.ufc.com/api/v1/us/fighters', {
    method: 'GET',
    headers: {
      'Content-type': 'application/json; charset=UTF-8',
      'mode': 'no-cors'
    },
    body: JSON.stringify({ 'string': string }),
  })
  .then(r => r.json())
  .then((data) => {
    this.setState({
      fighters: data,
    })
  })
  .catch((err) => console.log(err))
}
```

**Comment by gittheking** [comment]
@nickykwn if you are already gathering the info on _YOUR_ API(serve), why are you also trying to hit the API from your client as well? Also, if this is in a react component give us a code snippet of the _entire_ component.
